### PR TITLE
Allow laravel 9

### PR DESCRIPTION
**Pull request by lukasleitsch**
This PR allows using your package with Laravel 9.

### CODE REVIEW

**Comment by fotrino** [comment]
@asantibanez could you take a look at this please? 
Thank you!!

**Comment by dambridge** [comment]
Might be time to fork...

**Comment by striderxfossility** [comment]
@asantibanez

Please pull

**Comment by Freddyqt** [comment]
> @asantibanez
> 
> Please pull
> 
> for quick solution
> 
> in your composer.json change version to: `"asantibanez/laravel-blade-sortable": "dev-laravel-9",`
> 
> and then add add the bottom: ` "repositories": [ { "type": "vcs", "url": "https://github.com/lukasleitsch/laravel-blade-sortable.git" } ]`

Despues debe ejecutar "composer update" en la terminal

**Comment by Freddyqt** [comment]
> @asantibanez
> 
> Please pull
> 
> for quick solution
> 
> in your composer.json change version to: `"asantibanez/laravel-blade-sortable": "dev-laravel-9",`
> 
> and then add add the bottom: ` "repositories": [ { "type": "vcs", "url": "https://github.com/lukasleitsch/laravel-blade-sortable.git" } ]`

Then you must run "composer update" in the terminal. thanks!

**Comment by fotrino** [comment]
Hi @asantibanez could you please tag this release? Thanks 😀

**Pull request merged**
